services:
## Mosquitto MQTT
  mqtt:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /home/tapias/Documents/docker_rpi_test/data/mosquitto/config:/mosquitto/config
      - /home/tapias/Documents/docker_rpi_test/data/mosquitto/data:/mosquitto/data
      - /home/tapias/Documents/docker_rpi_test/data/mosquitto/log:/mosquitto/log
volumes:
  config:
  data:
  log:
